---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: mas-devops-configure-suite
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

  stepTemplate:
    env:
      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)

  steps:
    - name: configure-suite
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs
      command: ["/bin/bash", "-c"]
      args:
        - |-
          source /opt/app-root/src/env.sh
          ansible-playbook /opt/app-root/lib/python3.8/site-packages/ansible_collections/ibm/mas_devops/playbooks/mas/configure-suite.yml
          python3 /opt/app-root/src/save-junit-to-mongo.py

  workspaces:
    - name: configs
    - name: settings
