---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: mas-devops-configure-app
spec:
  params:
    - name: mas_app_id
      type: string
      description: Maximo Applicaiton Suite Application Id
    - name: mas_workspace_id
      type: string
      description: Maximo Application Suite Workspace Id
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

  stepTemplate:
    env:
      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)

      - name: MAS_WORKSPACE_ID
        value: $(params.mas_workspace_id)
      - name: MAS_APP_ID
        value: $(params.mas_app_id)

  steps:
    - args:
        - |-
          source /opt/app-root/src/env.sh
          ansible-playbook /opt/app-root/lib/python3.8/site-packages/ansible_collections/ibm/mas_devops/playbooks/mas/configure-app.yml
          python3 /opt/app-root/src/save-junit-to-mongo.py
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/ibmmas/ansible-devops:latest'
      imagePullPolicy: Always
      name: configure-app
      resources: {}
      workingDir: /workspace/configs

  workspaces:
    - name: settings
