namespace: ibm
name: mas_devops
version: 4.3.0
readme: README.md
authors:
  - David Parker <parkerda@uk.ibm.com>
  - Paul Stone
  - Tom Klapiscak
  - Caio Pereira <caiofcp@br.ibm.com>
  - Joao Paulo Karol Nunes
description: MAS DevOps Ansible Collection
license:
  - EPL-2.0
tags:
  - ibm
  - mas
  - rhocp
dependencies:
  "community.kubernetes": ">=1.2.1,<2.0.0"
repository: https://github.com/ibm-mas/ansible-devops
documentation: https://ibm-mas.github.io/ansible-devops/
homepage: https://ibm-mas.github.io/ansible-devops/
issues: https://github.com/ibm-mas/ansible-devops/issues
build_ignore: []
